version: '3' 
services:
  web:
    container_name: api-docker-njs
    restart: always
    build: .
    ports:
      - "4500:3000"
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app
  mongo:
    container_name: mymongodb
    image: mongo
    ports:
      - "27018:27017"
    logging: 
      driver: none